### ISSUE TITLE
Kubernetes v1.20.2

### ISSUE THREAD

**Issue by thesneakernet** [moosefs/moosefs-csi#10]
Deployment fails with StatefulSet and DaemonSet with the following errors:
unable to recognize "deploy/kubernetes/moosefs-csi-ep.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"
unable to recognize "deploy/kubernetes/moosefs-csi-ep.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"

I changed DaemonSet to apps/v1 and that seems to resolve the error message for DaemonSet but no DaemonSet is created when I use "kubectl get daemonsets -A"

 But StatefulSet complains with "error: error validating "deploy/kubernetes/moosefs-csi-ep.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false"

Does anyone know what the update needs to be for DaemonSet and StatefulSet to get this owrking in Kubernetes v1.20.2 with Containerd?

**Comment by nickb937** [comment]
Maybe try this version: https://github.com/Kunde21/moosefs-csi

**Comment by thesneakernet** [comment]
> 
> 
> Maybe try this version: https://github.com/Kunde21/moosefs-csi
> Similar issue: #8

Thanksf or the reply.  Sadly that version is having issues as well.  I tried the fixes in #8 but it fails with: error validating data: ValidationError(StatefulSet.spec): missing required field "selector" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by pkonopelko** [comment]
Hello, please check out the latest release we have pushed to the repository, retest and reopen the issue if needed. Thanks
