### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by antoinetran** [moosefs/moosefs-csi#6]
Hi,

The last commit has been over a year ago. Can we expect a tag? Thank you!

**Comment by antoinetran** [comment]
Hi, @maniankara @karolmajek is it possible to have a tag against the latest commit https://github.com/moosefs/moosefs-csi/commit/62bb6055987c164f1a354c09b6eab59b6c8ea302 ? Thank you!

**Comment by pkonopelko** [comment]
Hello @antoinetran,
We are working on the update for the MooseFS Containter Storage Interface driver (hence no tag yet), but the changes are not yet ready to be published. We will publish them once ready.

Piotr

**Comment by pkonopelko** [comment]
@antoinetran Please check out the latest release we have pushed to the repository. Thanks
