### ISSUE TITLE
k3s support?

### ISSUE THREAD

**Issue by dragon2611** [moosefs/moosefs-csi#8]
Is there any reason why this shouldn't work on k3s?

I think it's just a problem with the kubernetes version and the version of the api's moosefs is trying to use but I might be wrong.

I'm not however sure how i'd convert the the .yml to work with v1

`kubectl apply -f moosefs-csi-ep.yaml -n kube-system
customresourcedefinition.apiextensions.k8s.io/csinodeinfos.csi.storage.k8s.io created
storageclass.storage.k8s.io/moosefs-block-storage unchanged
serviceaccount/csi-moosefs-controller-sa created
serviceaccount/csi-moosefs-node-sa created
clusterrole.rbac.authorization.k8s.io/csi-moosefs-provisioner-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-moosefs-provisioner-binding created
clusterrole.rbac.authorization.k8s.io/csi-moosefs-attacher-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-moosefs-attacher-binding created
clusterrole.rbac.authorization.k8s.io/csi-moosefs-snapshotter-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-moosefs-snapshotter-binding created
clusterrole.rbac.authorization.k8s.io/csi-moosefs-driver-registrar-controller-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-moosefs-driver-registrar-controller-binding created
clusterrole.rbac.authorization.k8s.io/csi-moosefs-driver-registrar-node-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-moosefs-driver-registrar-node-binding created
unable to recognize "moosefs-csi-ep.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"
unable to recognize "moosefs-csi-ep.yaml": no matches for kind "DaemonSet" in version "apps/v1beta2"`

`root@k3s:~/moosefs-csi/deploy/kubernetes# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3+k3s1", GitCommit:"5b17a175ce333dfb98cb8391afeb1f34219d9275", GitTreeState:"clean", BuildDate:"2020-02-27T07:28:53Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Kunde21** [comment]
You're correct, kubernetes version 1.17 moved apps to v1.  Only a couple changes are needed.

For the Controller: 
```
 kind: StatefulSet
-apiVersion: apps/v1beta1
+apiVersion: apps/v1
 metadata:
   name: csi-moosefs-controller
   namespace: kube-system
 spec:
   serviceName: "csi-moosefs"
   replicas: 1
+  selector:
+    matchLabels:
+      app: csi-moosefs-controller
+      role: csi-moosefs
   template:
```

For the Node driver:
```
 ---
 kind: DaemonSet
-apiVersion: apps/v1beta2
+apiVersion: apps/v1
 metadata:
   name: csi-moosefs-node
```

**Comment by pkonopelko** [comment]
Hello, please check out the latest release we have pushed to the repository, retest and reopen the issue if needed. Thanks
